apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1 # number of pods we want to create running a particular image (3 pods of posts for example)
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vdeguil/ticketing-auth:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth' # no problem here, only accessible from inside cluster, no username or password here
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  type: ClusterIP # type default is ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000