apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.25.2
          args: [
            '-p', '4222', #server port
            '-m', '8222', #monitoring port
            '-hbi', '5s', #heartbeat healthcheck to connected clients => frequency of healthcheck send by server to clients
            '-hbt', '5s', #heartbeat => how long has the client to respond
            '-hbf', '2', #heartbeat => number of time each client can fail before considering the client process dead
            '-SD',
            '-cid', 'ticketing' #cluster id
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222