apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
spec:
  replicas: 1 # number of pods we want to create running a particular image (3 pods of posts for example)
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  type: ClusterIP # type default is ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017